### PR TITLE
Private server

### LINKED ISSUE #4: Private symbol server support
#### Is the feature request related to a problem

Cymbal currently doesn't download from private symbol servers. That's outlined in the readme and I see no mention (in documentation) of any way to change this behavior.

#### Describe the solution

Support downloading symbols from private symbol servers by permitting the user to specify the symbol server in a MSBuild property.

#### Describe alternatives considered

None, I can't think of an alternative for this issue.

#### Additional context

This permits private packages to be used where NuGet packages and symbols are on a private symbol server. I like this approach to packaging (the split packages), but I'm now missing the PDB files in production which reduces usability of logs and exception stack traces.

### PR DESCRIPTION
**Pull request by mycroes**
Add private symbol server support, fixes #4

### CODE REVIEW

**Comment by SimonCropp** [comment]
looks good. can u add some docs to the readme

**Comment by mycroes** [comment]
I did 😄 See d68b497a959260af32210de460bd62c1355f70a3 for details...

**Comment by SimonCropp** [comment]
thanks. deploying now

**Comment by mycroes** [comment]
Also, I was impressed by the readme and the tests. Good to see someone putting in the effort to produce a high quality experience.

**Comment by SimonCropp** [comment]
>  I'm not sure if net7 will actually cover this

only a small part of it https://github.com/SimonCropp/Cymbal/issues/7  ie it doesnt pre-download symbols 

> Also, I was impressed by the readme and the tests. Good to see someone putting in the effort to produce a high quality experience.

glad u like it. i try to keep that level of quality in all my projects https://www.nuget.org/profiles/simoncropp

**Pull request merged**
